account/urls.py
from django.urls import path 
from account.views import account_view


app_name = "account"

urlpatterns = [
    path('<user_id>' , account_view , name = 'view')
]

base/urls.py
from django.contrib import admin
from django.urls import path
from base import views
from django.urls import path , include
from django.conf import settings

from account.views import register_view , login_view , logout_view , account_search_view 

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('' , views.homeScreen , name="home"),
    path('login' , login_view , name="login"),
    path('logout' , logout_view , name="logout"),
    path('register' , register_view , name="register"),
    path('search' , account_search_view , name="search"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

livechatapp/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")),
    path('account', include('account.urls' , namespace='account')),
]

base/models.py
from django.db import models 

base/views.py
from django.shortcuts import render

def homeScreen(request):
    context={}
    return render(request ,  "home.html" , context)

def registerView(request):
    return render(request ,  "register.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>LiveChatApp</title>
</head>
<body>
    {% include 'header.html' %}
    
        {% block content %}
        
        {% endblock content %}
    </div>


    <style>
        body{
            background-color: var(--main-background-color);
            font-family:"Poppins";
            font-weight:380;
        }
        :root {
            --main-background-color: #f2f2f2;
            --dark-background-color: #a2a2a2;
            --second-text-color: #808080;
            --light-text-color: #0080ff;
        }
    </style>
</body>
</html>

templates/header.html
<div class="main">
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">{{username}}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                    <img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="pfp" width="40" height="40">
                </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href={% url 'home' %}>Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'register' %}>Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'account:view' user_id=request.user.id %}>Account</a>
              </li>
            </ul>
            <form class="search-bar d-flex" role="search"  onsubmit="return executrQuery();">
              <input class="form-control me-2" id="id_q_small" type="text" placeholder="Search" aria-label="Search" name="q">
            </form>
          </div>
        </div>
      </nav>


      <script>
        function executrQuery(){
            var query = document.getElementById("id_q_small").value;
            window.location.replace("{% url 'search' %}?q=" + query)
            return false

        }
      </script>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>you have logged in</h1>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<form class="form-signin" method="post">
    
    {% csrf_token %}
    
    <div class="d-flex flex-column pb-3">
        <img class="img-fluid mx-auto d-block" src="livechatapp\media\profile_image.png" alt="logo" width="72" height="72">
    </div>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

    {% for field in login_form %}
    <p>
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    {% if login_form.non_field_errors %}
    <div style="color: red">
    <p>{{login_form.non_field_errors}}</p>
    </div>

    {% endif %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
</form>

    <div class="d-flex flex-column my-4">
        <a class="m-auto" href="{% url 'password_reset' %}">Reset password</a>
    </div>

{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" >
    {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">username</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="username">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">confirm password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password2">
  </div>
  
  {% for field in registratiion_form %}
    <p>
      {% for error in field.errors %}
        <p style="color:red">
            {{error}}
        </p>
      {% endfor %}
    </p>
  {% endfor %}


  {% if refistration_form.non_field_errors %} 
    <div style="color:red">
      <p>
        {{refistration_form.non_field_errors}}
      </p>
    </div>
  {% endif %}

  
  <button type="submit" class="btn btn-primary">Submit</button>

</form>
{% endblock content %}
    